import { ArrowUpRight, Check, EyeOff, Fingerprint, LockKeyhole, ShieldCheck, Users } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function LandingPage() {
  return <div className="page">
    <section className="hero" aria-labelledby="hero-title">
      <div className="hero-copy"><div className="eyebrow">A private membership experiment</div><h1 id="hero-title" className="display">A room for the<br /><em>unseen.</em></h1><p className="lede">Stillroom lets an invited member prove they belong in a private screening room without publishing their score, secret, or social graph.</p><div className="actions"><Link className="button primary" to="/gate">Enter with a private pass <ArrowUpRight size={16} aria-hidden="true" /></Link><Link className="button" to="/philosophy">Read the privacy notes</Link></div><div className="hero-meta"><span>01</span> witness stays local <span>/</span><span>02</span> result is public <span>/</span><span>03</span> identity stays yours</div></div>
      <div className="image-frame hero-image"><img src="/images/alpine-frame.jpg" alt="A distant ridge and quiet mountain valley at dusk" /><div className="program-strip">PROGRAM 07 / THE RIDGELINE</div><div className="frame-note"><strong>SCREENING 07</strong>entry rule: private<br />status: accepting members</div></div>
    </section>
    <section className="section" aria-labelledby="program-title"><div className="section-heading"><div><div className="eyebrow">The house notes</div><h2 id="program-title">The room only keeps<br />what it needs.</h2></div><p>An organizer publishes the admission rule. A member brings the evidence. Midnight proves the match without turning the evidence into a public record.</p></div><div className="program-grid"><article className="program-card wide"><img src="/images/forest-frame.jpg" alt="Light passing between tall trees" /><div className="program-card-copy"><div className="card-top"><span>FEATURE / 01</span><span>PRIVATE ALLOWLIST</span></div><h3>The hidden credential</h3><p>Eligibility is committed by a curator before a member arrives. The score and secret never cross the public boundary.</p></div></article><article className="program-card"><div className="card-top"><span><Fingerprint size={18} aria-hidden="true" /></span><span>REPLAY GUARD</span></div><div><h3>One pass, one arrival.</h3><p>A gate-scoped nullifier makes reuse visible without exposing the passphrase that made it.</p></div><Link className="arrow-link" to="/gate">Try the member pass <ArrowUpRight size={14} aria-hidden="true" /></Link></article><article className="program-card"><div className="card-top"><span><EyeOff size={18} aria-hidden="true" /></span><span>SELECTIVE DISCLOSURE</span></div><div><h3>Reveal the result.</h3><p>The chain learns that the predicate passed. It does not learn the private value behind it.</p></div><Link className="arrow-link" to="/observatory">Visit the signal room <ArrowUpRight size={14} aria-hidden="true" /></Link></article></div></section>
    <div className="stat-row" aria-label="Stillroom principles"><div className="stat"><strong>00</strong><span>private scores published</span></div><div className="stat"><strong>01</strong><span>verifiable public outcome</span></div><div className="stat"><strong>32B</strong><span>nullifier address space</span></div></div>
    <section className="section" aria-labelledby="flow-title"><div className="section-heading"><div><div className="eyebrow">A four-part screening ritual</div><h2 id="flow-title">Less evidence.<br />More certainty.</h2></div></div><div className="principle-grid"><div className="principle"><strong>01 / Curate</strong><p>The organizer publishes a threshold, pass, expiry and capacity to the ledger.</p></div><div className="principle"><strong>02 / Prepare</strong><p>The member keeps their score and secret in a local proving session.</p></div><div className="principle"><strong>03 / Prove</strong><p>Compact checks the private predicate and records an unlinkable nullifier.</p></div></div></section>
    <section className="panel section-rule"><div className="eyebrow">A precise promise</div><h2>Stillroom is not a database<br />with a nicer door.</h2><p className="panel-copy">It is a small demonstration of privacy-first access. The member sees a clear admission result; the organizer sees capacity and proof, not a dossier.</p><div className="actions"><Link className="button primary" to="/operations"><LockKeyhole size={16} aria-hidden="true" /> Open operations</Link><Link className="button" to="/philosophy"><ShieldCheck size={16} aria-hidden="true" /> See what is public</Link></div></section>
  </div>;
}
