import { ExternalLink, Hash, RefreshCw, Radio, ShieldCheck } from 'lucide-react';
import { getContractAddress, getExplorerContractUrl } from '../config';
import { toHex } from '../lib/midnight';
import { useContractState } from '../hooks/useContractState';
import { CopyButton, EmptyState, Notice } from '../components/Kit';

export default function ObservatoryPage() {
  const address = getContractAddress();
  const { ledgerState, isLoading, error, lastUpdate, refetch } = useContractState(6000);
  const nullifiers: string[] = [];
  try { if (ledgerState?.used_nullifiers && Symbol.iterator in Object(ledgerState.used_nullifiers)) for (const item of ledgerState.used_nullifiers as any) nullifiers.push(toHex(item)); } catch { /* preserve an honest empty feed for changed indexer shapes */ }
  const entries = ledgerState?.screening_entries == null ? null : Number(ledgerState.screening_entries);
  const limit = ledgerState?.entry_limit == null ? null : Number(ledgerState.entry_limit);
  const fill = entries !== null && limit ? Math.min(100, entries / limit * 100) : 0;
  return <div className="page"><header className="page-header"><div className="eyebrow">Signal room / public state</div><h1 className="page-title">Watch the proof.<br /><em>Not the person.</em></h1><p className="page-intro">This room reflects only what the Stillroom contract intentionally makes public: its rule, capacity, aggregate activity and replay guards.</p></header>
    {!address && <Notice>No contract is configured on <strong>this network</strong>. Open Operations to deploy a screening, or set <span className="mono">VITE_CONTRACT_ADDRESS</span>.</Notice>}{error && <Notice kind="error">{error}</Notice>}
    <div className="metric-band" style={{ marginTop: 15 }}><div className="metric"><strong>{entries == null ? '—' : entries}</strong><span>admissions recorded</span></div><div className="metric"><strong>{limit == null ? '—' : limit}</strong><span>screening capacity</span></div><div className="metric"><strong>{ledgerState ? nullifiers.length : '—'}</strong><span>public nullifiers</span></div><div className="metric"><strong>{ledgerState ? ledgerState.gate_open ? 'OPEN' : 'PAUSED' : '—'}</strong><span>room status</span></div></div>
    <div className="workspace-grid"><section className="panel"><div className="panel-heading"><div className="eyebrow">Indexed configuration</div><button className="icon-button" onClick={() => void refetch()} aria-label="Refresh public state" title="Refresh"><RefreshCw size={16} /></button></div>{isLoading && !ledgerState ? <div className="empty-state"><Radio size={22} aria-hidden="true" /><h3>Listening for the room</h3><p>The indexer has not returned a state snapshot yet.</p></div> : !ledgerState ? <EmptyState title="No state to show">Deploy a screening to begin the public feed.</EmptyState> : <><div className="data-list"><div className="data-row"><span className="label">Contract</span><span className="copy-control"><a className="mono quiet-link" href={getExplorerContractUrl(address)} target="_blank" rel="noreferrer">{address.slice(0, 10)}… <ExternalLink size={13} /></a><CopyButton value={address} /></span></div><div className="data-row"><span className="label">Minimum signal</span><strong>{ledgerState.entry_threshold?.toString()} points</strong></div><div className="data-row"><span className="label">Pass identifier</span><strong className="mono">{toHex(ledgerState.access_pass_id).slice(0, 16)}…</strong></div><div className="data-row"><span className="label">Deadline</span><strong>{new Date(Number(ledgerState.entry_deadline) * 1000).toLocaleString()}</strong></div><div className="data-row"><span className="label">Edition</span><strong>{toHex(ledgerState.edition).replace(/\0/g, '').slice(0, 20)}</strong></div></div><div className="label" style={{ display: 'block', marginTop: 21 }}>Capacity used</div><div className="progress"><span style={{ width: `${fill}%` }} /></div><span className="mono" style={{ color: 'var(--faint)', fontSize: 10 }}>{fill.toFixed(1)}% of the public capacity</span></>}</section>
      <section className="panel"><div className="eyebrow">Admission feed</div><h2>Anonymous arrivals</h2><p className="panel-copy">Nullifiers are single-use replay guards, not identity records. They cannot be used here to reconstruct a private passphrase.</p>{nullifiers.length === 0 ? <EmptyState title="No arrivals yet"><ShieldCheck size={18} aria-hidden="true" /> The next successful proof will appear here as an unlinkable result.</EmptyState> : <div className="feed">{nullifiers.slice().reverse().map((item, index) => <div className="feed-item" key={item}><span className="feed-marker" aria-hidden="true" /><div><strong>Admission #{nullifiers.length - index} verified</strong><p><Hash size={11} aria-hidden="true" /> {item}</p></div></div>)}</div>}{lastUpdate && <div className="mono" style={{ color: 'var(--faint)', fontSize: 10, marginTop: 18 }}>LAST INDEXER READ · {lastUpdate.toLocaleTimeString()}</div>}</section></div>
  </div>;
}
