import { Eye, EyeOff, Fingerprint, Globe2, LockKeyhole, ShieldCheck } from 'lucide-react';

export default function PhilosophyPage() {
  return <div className="page"><header className="page-header"><div className="eyebrow">Privacy notes / read before proving</div><h1 className="page-title">The room can verify<br /><em>without watching you.</em></h1><p className="page-intro">Stillroom uses Midnight's public ledger and private witness model. The proof is public; the evidence used to make it is not.</p></header>
    <div className="privacy-columns"><section className="privacy-block public"><Globe2 size={22} color="var(--accent)" aria-hidden="true" /><h2>What the network sees</h2><p>These values are intentionally part of the public screening state. A visitor should be able to audit the rule before entering.</p><ul><li>threshold, expiry and capacity</li><li>screening pass and curator commitment</li><li>open or paused status</li><li>aggregate admission count</li><li>gate-scoped nullifier</li></ul></section><section className="privacy-block private"><LockKeyhole size={22} color="var(--positive)" aria-hidden="true" /><h2>What stays in the proof</h2><p>Witness values are supplied by the member's browser and used inside the circuit. They do not become circuit arguments or ledger fields.</p><ul><li>member's eligibility score</li><li>member secret and source credential</li><li>credential preimage</li><li>the private authorization witness</li><li>any personal reason for eligibility</li></ul></section></div>
    <section className="section"><div className="section-heading"><div><div className="eyebrow">The actual guarantee</div><h2>Privacy is not<br />invisibility.</h2></div><p>Midnight still exposes that a transaction happened, which circuit ran, when it ran, and what public state changed. Stillroom keeps that surface deliberate.</p></div><div className="program-grid"><article className="program-card"><Eye size={22} color="var(--accent)" aria-hidden="true" /><div><h3>Observers can verify</h3><p>That a private score cleared the public threshold, an organizer issued the credential, and the pass was not replayed.</p></div></article><article className="program-card"><EyeOff size={22} color="var(--positive)" aria-hidden="true" /><div><h3>Observers cannot recover</h3><p>The score, the secret, or the hidden credential behind an accepted admission proof.</p></div></article><article className="program-card"><Fingerprint size={22} color="var(--accent-soft)" aria-hidden="true" /><div><h3>Replay is observable</h3><p>A public nullifier records that a pass has been consumed. Its private preimage is never disclosed.</p></div></article></div></section>
    <section className="panel section-rule"><div className="eyebrow">Compact boundary</div><div className="code-block" style={{ marginTop: 18 }}><span className="code-accent">const</span> score = get_eligibility_score();<br /><span className="code-accent">const</span> secret = get_passphrase();<br /><span className="code-accent">const</span> credential = credential_commitment(score, secret, access_pass_id);<br /><span className="code-accent">assert</span>(credentials.member(credential));<br /><span className="code-accent">assert</span>(score &gt;= entry_threshold);<br /><br /><span className="code-accent">// only this result crosses the public boundary</span><br />screening_entries.increment(1);</div></section>
  </div>;
}
